"""
=============================================================================
MODULE 2 — DEMO & ATTACK SIMULATION SUITE
AES-256-CBC Encryption Engine
=============================================================================
Project : Secure Vehicle-to-Controller Message Exchange
Group   : 29 | EE8257 Information Security

Demonstrations:
  1.  Normal encrypt / decrypt (happy path)
  2.  Ciphertext randomness — same plaintext, different ciphertext each time
  3.  Tampered ciphertext detection (HMAC catches it)
  4.  IV-swap attack prevention
  5.  Wrong AES key failure
  6.  ECB vs CBC — pattern leakage comparison (Lecture 4 core demo)
  7.  IV reuse catastrophe — plaintext XOR leakage
  8.  PKCS7 padding internals walkthrough
  9.  Encrypt-then-MAC ordering demonstration
  10. Multi-vehicle encrypted session
  11. Packet wire serialisation / deserialisation round-trip

Run: python3 demo_aes.py
=============================================================================
"""

import json
import os
import secrets
import struct
import sys
import time
import copy

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))


from modules.aes_engine import (
    AESEngine,
    ECBDemoEngine,
    EncryptedPacket,
    VehicleEncryptor,
    ControllerDecryptor,
    generate_aes_key,
    generate_iv,
    generate_mac_key,
    _pkcs7_pad,
    _pkcs7_unpad,
    _aes_cbc_encrypt_raw,
    _aes_cbc_decrypt_raw,
    AES_BLOCK_SIZE,
)

# ── Terminal colours ───────────────────────────────────────────────────────
RESET  = "\033[0m";  BOLD = "\033[1m"
GREEN  = "\033[92m"; RED  = "\033[91m"; YELLOW = "\033[93m"
CYAN   = "\033[96m"; BLUE = "\033[94m"; GRAY   = "\033[90m"
WHITE  = "\033[97m"; MAGENTA = "\033[95m"

def hdr(t):  print(f"\n{BOLD}{BLUE}{'═'*70}\n  {t}\n{'═'*70}{RESET}")
def sub(t):  print(f"\n{BOLD}{CYAN}  ── {t} ──{RESET}")
def ok(m):   print(f"  {GREEN}✔  {m}{RESET}")
def fail(m): print(f"  {RED}✘  {m}{RESET}")
def info(m): print(f"  {YELLOW}ℹ  {m}{RESET}")
def dat(l,v):print(f"  {GRAY}{l:<26}{RESET} {WHITE}{v}{RESET}")
def warn(m): print(f"  {MAGENTA}⚠  {m}{RESET}")


# =============================================================================
# DEMO 1 — Normal Encryption / Decryption
# =============================================================================

def demo_normal():
    hdr("DEMO 1 — Normal AES-256-CBC Encryption & Decryption")

    print(f"""
  {GRAY}Scenario:{RESET}
  Vehicle VH-001 sends encrypted telemetry to the controller.
  The payload is encrypted with AES-256-CBC (K_s) and authenticated
  with HMAC-SHA256 (K_m) using the Encrypt-then-MAC pattern.

  {GRAY}Syllabus:{RESET} Lecture 4 — AES block cipher, CBC mode.
  Lecture 6 — HMAC integration (Encrypt-then-MAC).
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)

    sub("Step 1 — Key generation")
    dat("K_s (AES-256, first 8B):", K_s[:8].hex() + "...  [32 bytes / 256 bits]")
    dat("K_m (HMAC, first 8B):",    K_m[:8].hex() + "...  [32 bytes / 256 bits]")
    dat("K_s == K_m?",             str(K_s == K_m) + "  (must be False — key separation)")
    ok("Keys are distinct and generated by CSPRNG")

    sub("Step 2 — Vehicle encrypts telemetry")
    encryptor = VehicleEncryptor("VH-001", K_s, K_m)
    payload   = {
        "speed_kmh"   : 87.4,
        "latitude"    : 6.0535,
        "longitude"   : 80.2210,
        "fuel_pct"    : 63.2,
        "engine_temp" : 91.5,
        "zone"        : "B2",
    }

    packet = encryptor.send(payload)

    plaintext_bytes = json.dumps(payload, sort_keys=True).encode()
    dat("Plaintext (UTF-8):",   json.dumps(payload))
    dat("Plaintext length:",    f"{len(plaintext_bytes)} bytes")
    dat("IV (16 bytes):",       packet.iv.hex())
    dat("Ciphertext length:",   f"{len(packet.ciphertext)} bytes")
    dat("Ciphertext (first 16B):", packet.ciphertext[:16].hex() + "...")
    dat("HMAC tag:",            packet.hmac_tag.hex())
    dat("Sequence no.:",        str(packet.sequence_no))

    # Confirm plaintext is NOT visible in ciphertext
    info("Checking that plaintext bytes do not appear in ciphertext...")
    if plaintext_bytes[:8] in packet.ciphertext:
        warn("Plaintext prefix found in ciphertext — this should never happen!")
    else:
        ok("Plaintext is NOT visible in ciphertext — confidentiality achieved")

    sub("Step 3 — Controller decrypts and verifies")
    decryptor = ControllerDecryptor(K_s, K_m)
    result    = decryptor.receive(packet)

    dat("Status:",   result["status"])
    dat("Reason:",   result["reason"])
    dat("Payload:",  json.dumps(result["payload"]))

    if result["status"] == "OK":
        ok("Decryption and HMAC verification both passed")
        ok("Payload recovered identically to the original")
        assert result["payload"] == payload, "Payload mismatch!"
    else:
        fail(f"Unexpected: {result['reason']}")


# =============================================================================
# DEMO 2 — Ciphertext Randomness (IV randomisation)
# =============================================================================

def demo_randomness():
    hdr("DEMO 2 — Ciphertext Randomness via Fresh IV per Message")

    print(f"""
  {GRAY}Scenario:{RESET}
  VH-002 sends the IDENTICAL payload four times. In ECB mode,
  all four would produce identical ciphertext. In CBC with a fresh
  random IV, each encryption produces a unique ciphertext even
  though the plaintext and key are constant.

  {GRAY}Syllabus:{RESET} Lecture 4 — "IV is required to ensure that identical
  plaintexts encrypt to different ciphertexts."
  This is semantic security — the attacker learns nothing about
  message frequency or content from ciphertext patterns.
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)
    enc = VehicleEncryptor("VH-002", K_s, K_m)

    payload = {"status": "IDLE", "speed_kmh": 0.0}
    print()

    ciphertexts = []
    ivs         = []
    for i in range(4):
        pkt = enc.send(payload)
        ciphertexts.append(pkt.ciphertext)
        ivs.append(pkt.iv)
        dat(f"  Message {i+1} IV:",         pkt.iv.hex())
        dat(f"  Message {i+1} CT (first 16B):", pkt.ciphertext[:16].hex())
        print()

    # Verify all ciphertexts are distinct
    unique_cts = len(set(ciphertexts))
    unique_ivs = len(set(ivs))

    if unique_cts == 4 and unique_ivs == 4:
        ok(f"All 4 ciphertexts are unique (despite identical plaintext)")
        ok(f"All 4 IVs are unique (CSPRNG ensures unpredictability)")
        ok("Attacker cannot detect repeated transmissions — semantic security")
    else:
        fail(f"Collision detected! unique_cts={unique_cts} unique_ivs={unique_ivs}")


# =============================================================================
# DEMO 3 — Tampered Ciphertext Detection
# =============================================================================

def demo_tampering():
    hdr("DEMO 3 — Tampered Ciphertext Detection (HMAC Guards Decryption)")

    print(f"""
  {GRAY}Scenario:{RESET}
  Trudy intercepts the encrypted packet and flips a bit in the
  ciphertext, attempting to inject modified data. The HMAC check
  (computed over the ciphertext in Encrypt-then-MAC) catches this
  BEFORE any decryption is attempted.

  {GRAY}Syllabus:{RESET} Lecture 6 — HMAC provides integrity.
  Lecture 4 — CBC error propagation: "a bit error in ciphertext
  block i corrupts the decryption of blocks i and i+1".
  Our design catches the tampering at the HMAC layer, not via
  the CBC error propagation (which would still produce some
  decryptable blocks — a weaker detection method).
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)
    enc = VehicleEncryptor("VH-003", K_s, K_m)
    dec = ControllerDecryptor(K_s, K_m)

    sub("Step 1 — Original packet encrypted successfully")
    packet  = enc.send({"command": "OPEN_GATE", "zone": "C3"})
    result1 = dec.receive(packet)
    dat("Original status:", result1["status"])
    ok("Original packet accepted")

    sub("Step 2 — Trudy flips a byte in the ciphertext")
    tampered         = copy.deepcopy(packet)
    ct_list          = bytearray(tampered.ciphertext)
    target_byte      = len(ct_list) // 2        # middle of ciphertext
    original_byte    = ct_list[target_byte]
    ct_list[target_byte] ^= 0xFF               # flip all 8 bits
    tampered.ciphertext  = bytes(ct_list)

    info(f"Byte at position {target_byte}: 0x{original_byte:02X} → 0x{ct_list[target_byte]:02X}")
    info("Trudy cannot recompute HMAC without K_m — sends stale tag")

    sub("Step 3 — Controller rejects tampered packet at HMAC layer")
    # Use a fresh decryptor so the replay counter doesn't interfere —
    # we want to demonstrate HMAC_FAIL specifically, not REPLAY.
    dec2    = ControllerDecryptor(K_s, K_m)
    result2 = dec2.receive(tampered)
    dat("Tampered packet status:", result2["status"])
    dat("Reason:", result2["reason"][:80] + "...")

    if result2["status"] == "HMAC_FAIL":
        ok("Ciphertext tampering detected by HMAC BEFORE any decryption")
        ok("Padding oracle attack surface: ZERO (decrypt never called)")
        ok("Trudy's modified GATE command was NOT executed")
    else:
        fail("UNEXPECTED: tampered packet was accepted!")


# =============================================================================
# DEMO 4 — IV-Swap Attack Prevention
# =============================================================================

def demo_iv_swap():
    hdr("DEMO 4 — IV-Swap Attack Prevention")

    print(f"""
  {GRAY}Scenario:{RESET}
  In CBC mode, flipping a bit in the IV predictably flips the
  corresponding bit in the FIRST decrypted plaintext block.
  If the IV were NOT authenticated (not in HMAC scope), an attacker
  could manipulate the IV to corrupt targeted fields in block 1.

  Our design includes the IV in the HMAC scope:
    HMAC( IV || ciphertext || vehicle_id || seq || timestamp, K_m )
  So any IV modification invalidates the HMAC tag.

  {GRAY}Syllabus:{RESET} Lecture 4 — CBC decryption formula:
    P[0] = D(C[0], K) ⊕ IV
  Flipping bit j of IV flips bit j of P[0] — controllable by attacker
  WITHOUT modifying C[0]. The HMAC over IV prevents this.
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)
    enc = VehicleEncryptor("VH-004", K_s, K_m)
    dec = ControllerDecryptor(K_s, K_m)

    sub("Step 1 — Original packet")
    packet = enc.send({"action": "SET_SPEED", "value": 60})
    ok(f"IV: {packet.iv.hex()}")

    sub("Step 2 — Trudy flips bit 7 of the IV (targeting block 1 of plaintext)")
    tampered    = copy.deepcopy(packet)
    iv_list     = bytearray(tampered.iv)
    iv_list[0] ^= 0x80           # flip MSB of byte 0
    tampered.iv = bytes(iv_list)
    info(f"Original IV[0]: 0x{packet.iv[0]:02X}  →  Tampered IV[0]: 0x{tampered.iv[0]:02X}")

    sub("Step 3 — Controller rejects — IV modification invalidates HMAC")
    result = dec.receive(tampered)
    dat("Status:", result["status"])
    if result["status"] == "HMAC_FAIL":
        ok("IV-swap attack detected — IV is included in HMAC scope")
        ok("Attacker cannot selectively corrupt plaintext block 1")
    else:
        fail("UNEXPECTED: IV swap was accepted!")


# =============================================================================
# DEMO 5 — ECB vs CBC Pattern Leakage (Lecture 4 Core Demo)
# =============================================================================

def demo_ecb_vs_cbc():
    hdr("DEMO 5 — ECB Pattern Leakage vs CBC Confidentiality (Lecture 4)")

    print(f"""
  {GRAY}Core concept (Lecture 4):{RESET}
  ECB (Electronic Codebook): each 16-byte block encrypted
  independently with the same key. Identical input blocks → identical
  output blocks. Structural patterns survive into ciphertext.

  CBC (Cipher Block Chaining): each block XORed with the previous
  ciphertext block before encryption. Identical input blocks →
  completely different output blocks. No pattern leakage.

  This demo uses structured vehicle telemetry to show how ECB leaks
  the REPETITIVE STRUCTURE of vehicle messages while CBC does not.
    """)

    K_s     = generate_aes_key(32)
    ecb_eng = ECBDemoEngine(K_s)

    # Craft messages where some 16-byte blocks are IDENTICAL
    # "TELEMETRY|VH-00" is exactly 16 bytes
    base_block   = b"TELEMETRY|VH-00X"   # 16 bytes exactly
    assert len(base_block) == 16

    # Three messages that share the same first block
    messages = [
        base_block + b"speed=087.4km/h|fuel=063%|zone=B2|temp=091.5",
        base_block + b"speed=087.4km/h|fuel=063%|zone=B2|temp=091.5",   # same
        base_block + b"speed=100.0km/h|fuel=040%|zone=A1|temp=095.2",   # different suffix
    ]

    sub("ECB mode — identical blocks produce identical ciphertext")
    ecb_results = []
    for i, msg in enumerate(messages):
        ct = ecb_eng.encrypt_ecb(msg)
        ecb_results.append(ct)
        block0_hex = ct[:16].hex()
        block1_hex = ct[16:32].hex()
        print(f"  {GRAY}Msg {i+1} Block0 (ECB):{RESET} {WHITE}{block0_hex}{RESET}")
        print(f"  {GRAY}Msg {i+1} Block1 (ECB):{RESET} {WHITE}{block1_hex}{RESET}")
        print()

    # Check if block 0 of messages 1 and 2 are identical (they share the same plaintext block)
    if ecb_results[0][:16] == ecb_results[1][:16] == ecb_results[2][:16]:
        warn("ECB: All 3 message header blocks are IDENTICAL in ciphertext!")
        warn("Attacker can detect: 'same vehicle type / same message prefix'")
        warn("Even without the key — pure ciphertext pattern analysis")
    print()

    sub("CBC mode — identical blocks produce DIFFERENT ciphertext")
    # For CBC we need a proper AES engine
    K_m    = generate_mac_key(32)
    engine = AESEngine(K_s, K_m)

    cbc_results = []
    for i, msg in enumerate(messages):
        pkt = engine.encrypt(msg, f"VH-{i:03d}", i + 1)
        cbc_results.append(pkt)
        block0_hex = pkt.ciphertext[:16].hex()
        block1_hex = pkt.ciphertext[16:32].hex() if len(pkt.ciphertext) >= 32 else "N/A"
        print(f"  {GRAY}Msg {i+1} Block0 (CBC):{RESET} {WHITE}{block0_hex}{RESET}")
        print(f"  {GRAY}Msg {i+1} Block1 (CBC):{RESET} {WHITE}{block1_hex}{RESET}")
        print(f"  {GRAY}Msg {i+1} IV    (CBC):{RESET} {CYAN}{pkt.iv.hex()}{RESET}")
        print()

    # Block 0 of messages 1 and 2 must be DIFFERENT (different IVs)
    if cbc_results[0].ciphertext[:16] != cbc_results[1].ciphertext[:16]:
        ok("CBC: All blocks are UNIQUE — even for identical input blocks")
        ok("Attacker cannot detect repeated messages or structure")
        ok("Semantic security achieved: ciphertext reveals NOTHING about plaintext")
    else:
        fail("UNEXPECTED: CBC produced identical blocks!")

    sub("Visual block comparison summary")
    print(f"  {'Message pair':<20} {'ECB Block0 same?':<22} {'CBC Block0 same?'}")
    print(f"  {'-'*60}")
    for i in range(len(messages)):
        for j in range(i+1, len(messages)):
            ecb_same = "YES ← LEAKS!" if ecb_results[i][:16] == ecb_results[j][:16] else "No"
            cbc_same = "YES" if cbc_results[i].ciphertext[:16] == cbc_results[j].ciphertext[:16] else "No ✔"
            print(f"  Msg {i+1} vs Msg {j+1}:          {ecb_same:<22} {cbc_same}")


# =============================================================================
# DEMO 6 — IV Reuse Catastrophe (XOR Leakage)
# =============================================================================

def demo_iv_reuse():
    hdr("DEMO 6 — IV Reuse Vulnerability (Plaintext XOR Leakage)")

    print(f"""
  {GRAY}Scenario:{RESET}
  A BROKEN implementation reuses the same IV for two messages.
  If an attacker knows one plaintext (a common assumption — known-
  plaintext attack), they can XOR the two ciphertexts to recover
  the other plaintext. This is identical to the OTP two-time pad
  vulnerability discussed in Lecture 3.

  Formula:
    C1[0] = E(P1[0] ⊕ IV, K)
    C2[0] = E(P2[0] ⊕ IV, K)
    C1[0] ⊕ C2[0] = E(P1[0] ⊕ IV, K) ⊕ E(P2[0] ⊕ IV, K)

  When IV is reused, the inner ⊕ IV terms cancel:
    The E() function creates a one-time pad stream from (P[i-1], K)
    → XOR of two ciphertexts = XOR of two plaintexts
    → If P1[0] is KNOWN, P2[0] = C1[0] ⊕ C2[0] ⊕ P1[0]

  {GRAY}Syllabus:{RESET} Lecture 3 — "OTP depth attack: if two messages are
  encrypted with the same OTP key, XOR of ciphertexts = XOR of
  plaintexts." CBC with reused IV is IDENTICAL to this attack.
  Our design calls generate_iv() for every message — this demo
  shows what happens when this rule is broken.
    """)

    K_s = generate_aes_key(32)

    # ── Reuse the SAME IV for two messages ─────────────────────────────
    REUSED_IV   = generate_iv()   # a single IV used twice (WRONG!)
    plaintext_1 = b"speed=087 zone=B2"    # Trudy knows this (known-plaintext)
    plaintext_2 = b"speed=999 zone=A0"    # this is the SECRET message

    # Pad both
    p1_padded = _pkcs7_pad(plaintext_1)
    p2_padded = _pkcs7_pad(plaintext_2)

    # Encrypt both with SAME IV (simulating broken implementation)
    ct1 = _aes_cbc_encrypt_raw(p1_padded, K_s, REUSED_IV)
    ct2 = _aes_cbc_encrypt_raw(p2_padded, K_s, REUSED_IV)

    sub("Setup — broken system reuses IV")
    dat("Plaintext 1 (known):", plaintext_1.decode())
    dat("Plaintext 2 (secret):",plaintext_2.decode())
    dat("Reused IV:",           REUSED_IV.hex())
    dat("Ciphertext 1 (16B):",  ct1[:16].hex())
    dat("Ciphertext 2 (16B):",  ct2[:16].hex())

    sub("Attack — Trudy XORs ciphertexts and known plaintext (block 1 only)")
    # XOR of block 0 ciphertexts
    xor_cts   = bytes(a ^ b for a, b in zip(ct1[:16], ct2[:16]))
    # XOR with known plaintext 1 padded to 16 bytes
    p1_block0 = p1_padded[:16]
    recovered = bytes(a ^ b for a, b in zip(xor_cts, p1_block0))

    dat("CT1 ⊕ CT2 (block 0):", xor_cts.hex())
    dat("(CT1⊕CT2) ⊕ P1[0]:", recovered.decode(errors='replace'))

    if recovered == p2_padded[:16]:
        warn("IV REUSE ATTACK SUCCEEDED — secret block 1 recovered!")
        warn(f"Recovered: '{recovered.decode(errors='replace')}'")
        warn("This is exactly the OTP two-time pad attack from Lecture 3!")
    print()

    sub("Our implementation — fresh IV prevents this attack")
    iv1 = generate_iv()
    iv2 = generate_iv()     # DIFFERENT IV
    ct1_safe = _aes_cbc_encrypt_raw(p1_padded, K_s, iv1)
    ct2_safe = _aes_cbc_encrypt_raw(p2_padded, K_s, iv2)
    xor_safe = bytes(a ^ b for a, b in zip(ct1_safe[:16], ct2_safe[:16]))
    # XOR of ciphertexts with different IVs produces garbage, not plaintext XOR
    garbage = bytes(a ^ b for a, b in zip(xor_safe, p1_block0))
    dat("Safe CT1 ⊕ CT2 ⊕ P1[0]:", garbage.decode(errors='replace')[:30] + "...")
    ok("With distinct random IVs, XOR-based attack produces garbage")
    ok("generate_iv() called once per message prevents IV reuse entirely")


# =============================================================================
# DEMO 7 — PKCS7 Padding Internals
# =============================================================================

def demo_padding():
    hdr("DEMO 7 — PKCS7 Padding Internals")

    print(f"""
  {GRAY}AES block size = 16 bytes. All inputs must be padded to a multiple
  of 16 bytes. PKCS7: append N bytes each of value N, where N is the
  number of bytes needed. If already aligned, append 16 bytes of 0x10.{RESET}
    """)

    test_cases = [
        b"speed=87.4",                          # 10 bytes  → pad 6
        b"VH-001|TELEMETRY|B2",                # 20 bytes  → pad 12
        b"A" * 16,                              # 16 bytes  → pad 16 (full block)
        b"B" * 31,                              # 31 bytes  → pad 1
        b"C" * 32,                              # 32 bytes  → pad 16
    ]

    sub("Padding examples")
    print()
    for msg in test_cases:
        padded = _pkcs7_pad(msg)
        n      = padded[-1]            # last byte IS the pad value
        unp    = _pkcs7_unpad(padded)
        ok_str = "✔" if unp == msg else "✘"

        print(f"  {GRAY}Input:  {RESET}{WHITE}{repr(msg[:24])}{'...' if len(msg)>24 else ''}{RESET}")
        print(f"  {GRAY}Length: {len(msg)} → padded: {len(padded)} bytes "
              f"(pad value N={n}, 0x{n:02X}){RESET}")
        print(f"  {GRAY}Last 4 padded bytes: {padded[-4:].hex()}  "
              f"Round-trip {ok_str}{RESET}")
        print()

    ok("PKCS7 always produces block-aligned output")
    ok("Unpadding is unambiguous — last byte always encodes the pad length")
    ok("Padding oracle attack: prevented by Encrypt-then-MAC (HMAC checked before unpad)")


# =============================================================================
# DEMO 8 — Encrypt-then-MAC Ordering
# =============================================================================

def demo_etm_ordering():
    hdr("DEMO 8 — Encrypt-then-MAC vs MAC-then-Encrypt Comparison")

    print(f"""
  {GRAY}The order of encryption and MAC computation critically affects
  security. Three schemes exist:{RESET}

  {GREEN}Encrypt-then-MAC (EtM) — THIS PROJECT:{RESET}
    MAC = HMAC(IV || ciphertext, K_m)
    Receiver: verify MAC → then decrypt
    ✔ No decryption oracle exposed to attacker
    ✔ Immune to padding oracle attacks (POODLE, Lucky13, BEAST)
    ✔ Used in: TLS 1.3, IPSec ESP, SSH (recommended extensions)

  {RED}MAC-then-Encrypt (MtE) — DEPRECATED:{RESET}
    MAC = HMAC(plaintext, K_m)
    Ciphertext = AES(plaintext || MAC, K_s)
    Receiver must decrypt BEFORE verifying MAC
    ✘ Exposes padding oracle — POODLE attack (2014) exploited this
    ✘ Used in TLS 1.2 (now deprecated), SSL 3.0 (broken)

  {RED}Encrypt-and-MAC (E&M) — SSH default:{RESET}
    MAC = HMAC(plaintext, K_m)   ← MAC over PLAINTEXT
    Ciphertext = AES(plaintext, K_s)
    ✘ MAC leaks plaintext information (deterministic function of plaintext)
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)
    engine = AESEngine(K_s, K_m)

    payload = b'{"command": "BRAKE", "force": 0.8}'
    packet  = engine.encrypt(payload, "VH-007", 1)

    sub("Our EtM implementation — verifying order")
    dat("HMAC scope includes:", "IV + ciphertext + vehicle_id + seq + timestamp")
    dat("HMAC covers plaintext?","No — HMAC is over CIPHERTEXT (EtM)")
    dat("Decrypt attempted if HMAC fails?", "No — ValueError raised immediately")
    ok("Encrypt-then-MAC correctly implemented — padding oracle impossible")

    # Demonstrate: if we tamper, decrypt is NEVER called
    sub("Confirming decryption is skipped on HMAC failure")
    bad = copy.deepcopy(packet)
    bad.ciphertext = b'\x00' * len(bad.ciphertext)
    try:
        engine.decrypt(bad)
        fail("UNEXPECTED: decryption succeeded on tampered packet")
    except ValueError as e:
        ok(f"decrypt() raised ValueError at HMAC check — AES never ran")
        info(f"Error: {str(e)[:70]}")


# =============================================================================
# DEMO 9 — Wire Packet Serialisation Round-Trip
# =============================================================================

def demo_serialisation():
    hdr("DEMO 9 — Packet Wire Serialisation / Deserialisation")

    print(f"""
  {GRAY}In the full system (Module 4), EncryptedPacket objects are
  serialised to bytes for TCP socket transmission. This demo
  verifies the to_bytes() / from_bytes() round-trip preserves
  all fields exactly, including IV, ciphertext, HMAC, and metadata.{RESET}
    """)

    K_s = generate_aes_key(32)
    K_m = generate_mac_key(32)
    enc = VehicleEncryptor("VH-008", K_s, K_m)
    dec = ControllerDecryptor(K_s, K_m)

    packet      = enc.send({"alert": "ENGINE_OVERHEAT", "temp_c": 112.4})
    wire_bytes  = packet.to_bytes()
    recovered   = EncryptedPacket.from_bytes(wire_bytes)

    sub("Serialisation")
    dat("Packet wire size:", f"{len(wire_bytes)} bytes total on wire")
    dat("  of which IV:",         f"{len(packet.iv)} bytes")
    dat("  of which ciphertext:", f"{len(packet.ciphertext)} bytes")
    dat("  of which HMAC tag:",   f"{len(packet.hmac_tag)} bytes")
    dat("  of which metadata:",   f"{len(wire_bytes) - len(packet.iv) - len(packet.ciphertext) - len(packet.hmac_tag)} bytes")

    sub("Round-trip field verification")
    fields = ["iv", "ciphertext", "hmac_tag", "vehicle_id", "sequence_no"]
    for f in fields:
        orig = getattr(packet, f)
        recv = getattr(recovered, f)
        if orig == recv:
            ok(f"{f}: preserved exactly")
        else:
            fail(f"{f}: MISMATCH!")

    sub("Decryption of deserialised packet")
    result = dec.receive(recovered)
    dat("Status:", result["status"])
    if result["status"] == "OK":
        ok("Full pipeline: encrypt → serialise → deserialise → decrypt: SUCCESS")
    else:
        fail(f"Pipeline failed: {result['reason']}")


# =============================================================================
# DEMO 10 — Multi-Vehicle Encrypted Session
# =============================================================================

def demo_multi_vehicle():
    hdr("DEMO 10 — Multi-Vehicle Encrypted Session")

    print(f"""
  {GRAY}Scenario:{RESET}
  Three vehicles each have unique AES and MAC key pairs.
  The controller handles all three simultaneously, maintaining
  separate replay counters per vehicle.
    """)

    vehicles = {
        "VH-010": (generate_aes_key(32), generate_mac_key(32)),
        "VH-011": (generate_aes_key(32), generate_mac_key(32)),
        "VH-012": (generate_aes_key(32), generate_mac_key(32)),
    }

    encryptors = {
        vid: VehicleEncryptor(vid, ks, km)
        for vid, (ks, km) in vehicles.items()
    }
    decryptors = {
        vid: ControllerDecryptor(ks, km)
        for vid, (ks, km) in vehicles.items()
    }

    messages = [
        ("VH-010", {"speed": 55.0, "zone": "A1"}),
        ("VH-011", {"speed": 72.3, "zone": "B2"}),
        ("VH-010", {"alert": "BRAKE_WARN"}),
        ("VH-012", {"speed": 90.0, "zone": "C3"}),
        ("VH-011", {"speed": 68.1, "fuel": 42.0}),
        ("VH-012", {"status": "IDLE"}),
    ]

    print()
    for vid, payload in messages:
        pkt    = encryptors[vid].send(payload)
        result = decryptors[vid].receive(pkt)
        status_str = f"{GREEN}OK{RESET}" if result["status"] == "OK" else f"{RED}{result['status']}{RESET}"
        print(f"  {GRAY}{vid}{RESET}  seq={pkt.sequence_no}  "
              f"ct={len(pkt.ciphertext)}B  "
              f"status={status_str}  "
              f"payload={json.dumps(result['payload'])}")

    sub("Cross-vehicle key isolation test")
    # VH-010's packet should be rejected by VH-011's decryptor
    pkt_010 = encryptors["VH-010"].send({"test": True})
    result_cross = decryptors["VH-011"].receive(pkt_010)
    if result_cross["status"] == "HMAC_FAIL":
        ok("Cross-vehicle key isolation confirmed — VH-010 packet rejected by VH-011 decryptor")
    else:
        fail("UNEXPECTED: cross-vehicle packet accepted!")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print(f"""
{BOLD}{BLUE}
╔══════════════════════════════════════════════════════════════════════╗
║   EE8257 Information Security — Group 29                            ║
║   Module 2: AES-256-CBC Encryption Engine                           ║
║   Secure Vehicle-to-Controller Message Exchange                     ║
╚══════════════════════════════════════════════════════════════════════╝
{RESET}""")

    demo_normal()
    demo_randomness()
    demo_tampering()
    demo_iv_swap()
    demo_ecb_vs_cbc()
    demo_iv_reuse()
    demo_padding()
    demo_etm_ordering()
    demo_serialisation()
    demo_multi_vehicle()

    hdr("ALL DEMOS COMPLETE")
    print(f"""
  {GREEN}{BOLD}Security guarantees demonstrated:{RESET}
  {GREEN}✔{RESET}  Confidentiality     — AES-256-CBC hides all payload content
  {GREEN}✔{RESET}  Semantic security   — fresh IV ensures identical plaintexts → different ciphertexts
  {GREEN}✔{RESET}  Integrity           — HMAC over ciphertext catches any modification
  {GREEN}✔{RESET}  IV authentication   — IV in HMAC scope prevents IV-swap attacks
  {GREEN}✔{RESET}  No padding oracle   — Encrypt-then-MAC: decrypt never runs on tampered input
  {GREEN}✔{RESET}  Key separation      — K_s ≠ K_m enforced in AESEngine constructor
  {GREEN}✔{RESET}  ECB weakness shown  — pattern leakage demonstrated and contrasted with CBC
  {GREEN}✔{RESET}  IV reuse attack     — demonstrated and mitigated by per-message generate_iv()
  {GREEN}✔{RESET}  Wire compatibility  — serialisation round-trip verified
  {GREEN}✔{RESET}  Multi-vehicle       — per-vehicle key isolation confirmed

  {CYAN}Next:{RESET} Module 3 — RSA Handshake & Session Key Exchange
  K_s and K_m will be transmitted securely using RSA public key
  encryption, completing the hybrid encryption system.
    """)
